# Generated by Django 5.1.15 on 2026-07-03 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text="Emoji or icon name for the UI — e.g. '🎮' or 'gaming'", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden from the dashboard and skipped during ingestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategorySourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('hackernews', 'Hacker News'), ('youtube', 'YouTube'), ('arxiv', 'arXiv'), ('pubmed', 'PubMed'), ('tmdb', 'TMDB'), ('nasa', 'NASA')], max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sources are skipped during ingestion for this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_configs', to='categories.category')),
            ],
            options={
                'verbose_name': 'category source config',
                'verbose_name_plural': 'category source configs',
                'db_table': 'categories_source_config',
                'ordering': ['category__name', 'source'],
                'unique_together': {('category', 'source')},
            },
        ),
        migrations.CreateModel(
            name='SubredditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit', models.CharField(help_text="Subreddit name without r/ prefix — e.g. 'programming'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive subreddits are skipped during ingestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreddit_configs', to='categories.category')),
            ],
            options={
                'verbose_name': 'subreddit config',
                'verbose_name_plural': 'subreddit configs',
                'db_table': 'categories_subreddit_config',
                'ordering': ['category__name', 'subreddit'],
                'unique_together': {('category', 'subreddit')},
            },
        ),
        migrations.CreateModel(
            name='UserCategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user category preference',
                'verbose_name_plural': 'user category preferences',
                'db_table': 'categories_user_preference',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
