# Generated by Django 5.1.15 on 2026-07-04 01:23

from typing import Any

from django.db import migrations, models


def remove_reddit_source_configs(apps: Any, schema_editor: Any) -> None:
    CategorySourceConfig = apps.get_model('categories', 'CategorySourceConfig')
    CategorySourceConfig.objects.filter(source='reddit').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_reddit_source_configs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='categorysourceconfig',
            name='source',
            field=models.CharField(choices=[('hackernews', 'Hacker News'), ('youtube', 'YouTube'), ('arxiv', 'arXiv'), ('pubmed', 'PubMed'), ('tmdb', 'TMDB'), ('nasa', 'NASA')], max_length=50),
        ),
        migrations.DeleteModel(
            name='SubredditConfig',
        ),
    ]
