# Generated by Django 5.1.15 on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_categorysourceconfig_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorysourceconfig",
            name="source",
            field=models.CharField(
                choices=[
                    ("hackernews", "Hacker News"),
                    ("devto", "DEV"),
                    ("youtube", "YouTube"),
                    ("arxiv", "arXiv"),
                    ("pubmed", "PubMed"),
                    ("tmdb", "TMDB"),
                    ("nasa", "NASA"),
                ],
                max_length=50,
            ),
        ),
    ]
