# Generated by Django 5.1.15 on 2026-07-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='categories.category')),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='ingestion.ingestionrun')),
            ],
            options={
                'verbose_name': 'trend snapshot',
                'verbose_name_plural': 'trend snapshots',
                'db_table': 'trends_snapshot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('hackernews', 'Hacker News'), ('youtube', 'YouTube'), ('arxiv', 'arXiv'), ('pubmed', 'PubMed'), ('tmdb', 'TMDB'), ('nasa', 'NASA')], max_length=50)),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=2000)),
                ('external_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('score', models.BigIntegerField(default=0)),
                ('score_label', models.CharField(default='score', max_length=50)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trends.trendsnapshot')),
            ],
            options={
                'verbose_name': 'trend item',
                'verbose_name_plural': 'trend items',
                'db_table': 'trends_item',
                'ordering': ['snapshot', 'rank'],
            },
        ),
        migrations.AddIndex(
            model_name='trendsnapshot',
            index=models.Index(fields=['category', 'source', '-created_at'], name='trends_snap_categor_3f87c3_idx'),
        ),
        migrations.AddIndex(
            model_name='trenditem',
            index=models.Index(fields=['snapshot', 'rank'], name='trends_item_snapsho_6d0f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='trenditem',
            index=models.Index(fields=['snapshot', 'source', 'rank'], name='trends_item_snapsho_8a0a3c_idx'),
        ),
    ]
