# Generated by Django 5.1.15 on 2026-07-04 01:23

from typing import Any

from django.db import migrations, models


def remove_reddit_trend_items(apps: Any, schema_editor: Any) -> None:
    TrendItem = apps.get_model('trends', 'TrendItem')
    TrendItem.objects.filter(source='reddit').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_reddit_trend_items, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trenditem',
            name='source',
            field=models.CharField(choices=[('hackernews', 'Hacker News'), ('youtube', 'YouTube'), ('arxiv', 'arXiv'), ('pubmed', 'PubMed'), ('tmdb', 'TMDB'), ('nasa', 'NASA')], max_length=50),
        ),
    ]
