# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trends", "0003_alter_trenditem_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trenditem",
            name="source",
            field=models.CharField(
                choices=[
                    ("hackernews", "Hacker News"),
                    ("devto", "DEV"),
                    ("nytimes", "New York Times"),
                    ("youtube", "YouTube"),
                    ("arxiv", "arXiv"),
                    ("pubmed", "PubMed"),
                    ("tmdb", "TMDB"),
                    ("nasa", "NASA"),
                ],
                max_length=50,
            ),
        ),
    ]
