# Generated by Codex on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trends", "0005_alter_trenditem_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trenditem",
            name="source",
            field=models.CharField(
                choices=[
                    ("hackernews", "Hacker News"),
                    ("devto", "DEV"),
                    ("nytimes", "New York Times"),
                    ("rawg", "RAWG"),
                    ("football_data", "Football-Data"),
                    ("youtube", "YouTube"),
                    ("arxiv", "arXiv"),
                    ("pubmed", "PubMed"),
                    ("tmdb", "TMDB"),
                    ("nasa", "NASA"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="trenditem",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional source-specific display fields, e.g. football match details.",
            ),
        ),
    ]
