# Generated by Django 5.1.15 on 2026-07-10 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_categorysourceconfig_source'),
        ('trends', '0006_alter_trenditem_source_trenditem_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('model_name', models.CharField(max_length=100)),
                ('input_item_count', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='categories.category')),
            ],
            options={
                'verbose_name': 'category AI summary',
                'verbose_name_plural': 'category AI summaries',
                'db_table': 'trends_category_ai_summary',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['category', '-generated_at'], name='trends_cate_categor_6900c4_idx')],
            },
        ),
    ]
