# Generated by Django 5.1.15 on 2026-07-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0007_categoryaisummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trenditem',
            name='source',
            field=models.CharField(choices=[('hackernews', 'Hacker News'), ('devto', 'DEV'), ('nytimes', 'New York Times'), ('rawg', 'RAWG'), ('football_data', 'Football-Data')], max_length=50),
        ),
    ]
