# Generated by Django 5.1.15 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0008_alter_trenditem_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trenditem",
            name="source",
            field=models.CharField(
                choices=[
                    ("hackernews", "Hacker News"),
                    ("devto", "DEV"),
                    ("nytimes", "New York Times"),
                    ("rawg", "RAWG"),
                    ("football_data", "Football-Data"),
                    ("cricket_data", "Cricket Data"),
                ],
                max_length=50,
            ),
        ),
    ]
