"""
backend/apps/trends/admin.py
──────────────────────────────
Purpose : Registers trend-related models in the Django admin panel.
          The most important admin registration in the whole project — this is
          where staff can see exactly what data the ingestion job produced
          and debug any issues (FR-19).

          What admins can see here:
            - TrendSnapshot: the snapshot records per category per day
            - TrendItem: individual trending posts, with source, score, URL
            - CategoryAISummary: stored Gemini summaries generated by ingestion

Used by : Django admin panel — loaded automatically by Django at startup
          Staff users — use this daily to verify ingestion health

Phase    : 1 — Week 2 (register as soon as models exist)
"""
from typing import TYPE_CHECKING, TypeAlias

from django.contrib import admin

from .models import CategoryAISummary, TrendItem, TrendSnapshot

if TYPE_CHECKING:
    CategoryAISummaryModelAdmin: TypeAlias = admin.ModelAdmin[CategoryAISummary]  # noqa: UP040
    TrendSnapshotModelAdmin: TypeAlias = admin.ModelAdmin[TrendSnapshot]  # noqa: UP040
    TrendItemModelAdmin: TypeAlias = admin.ModelAdmin[TrendItem]  # noqa: UP040
else:
    CategoryAISummaryModelAdmin = admin.ModelAdmin
    TrendSnapshotModelAdmin = admin.ModelAdmin
    TrendItemModelAdmin = admin.ModelAdmin


@admin.register(TrendSnapshot)
class TrendSnapshotAdmin(TrendSnapshotModelAdmin):
    list_display = ("category", "source", "ingestion_run", "created_at")
    list_filter = ("source", "category", "created_at")
    search_fields = ("category__name", "source")
    autocomplete_fields = ("category", "ingestion_run")
    ordering = ("-created_at",)


@admin.register(TrendItem)
class TrendItemAdmin(TrendItemModelAdmin):
    list_display = ("title", "source", "snapshot", "score", "score_label", "rank", "created_at")
    list_filter = ("source", "score_label", "created_at")
    search_fields = ("title", "url", "external_url")
    autocomplete_fields = ("snapshot",)
    readonly_fields = ("created_at",)
    ordering = ("snapshot", "rank")


@admin.register(CategoryAISummary)
class CategoryAISummaryAdmin(CategoryAISummaryModelAdmin):
    list_display = ("category", "model_name", "input_item_count", "generated_at")
    list_filter = ("model_name", "generated_at")
    search_fields = ("category__name", "summary_text")
    autocomplete_fields = ("category",)
    readonly_fields = ("generated_at",)
    ordering = ("-generated_at",)
