# Generated by Django 5.1.15 on 2026-07-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_adapter', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('items_fetched', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='categories.category')),
            ],
            options={
                'verbose_name': 'ingestion run',
                'verbose_name_plural': 'ingestion runs',
                'db_table': 'ingestion_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['category', 'source_adapter', '-started_at'], name='ingestion_r_categor_0c0a14_idx'), models.Index(fields=['status', '-started_at'], name='ingestion_r_status_fb49a7_idx')],
            },
        ),
    ]
